[package]
name = "audiolib"
version = "0.1.0"
edition = "2021"
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

# ASIO requirements
[target.'cfg(target_os = "windows")'.dependencies]
cpal = { version = "0.13.4", features = ["asio"] }
clang-sys = "0.29.3"
[target.'cfg(not(target_os = "windows"))'.dependencies]
cpal = { version = "0.13.4"}

[dependencies]
ringbuf = "0.2.6"
# hound = "3.4"
assert_no_alloc = {version = "1.1.2", features = ["warn_debug"]}
fastrand = "1.5.0"
bit_mask_ring_buf = "0.5"


# enabling this flag will increase performance by a lot
# RUSTFLAGS="-C target-cpu=native" cargo build --release

[profile.release]
# these dont seem to help much
# lto = "thin"
# codegen-units = 1
# panic = "abort"