[package]
name = "audiolib"
version = "0.1.0"
edition = "2021"
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
cpal = { version = "0.13.4", features = ["asio"] }
clang-sys = "0.29.3"
anyhow = "1.0.12"
ringbuf = "0.2.6"
hound = "3.4"
assert_no_alloc = {version = "1.1.2", features = ["warn_debug"]}
rand = "0.8.4"
# itertools = "0.8"
